apiVersion: v1
kind: Service
metadata:
  name: flask-nodeport-service
  namespace: flask-project
spec:
  selector:
      app: flaskapp-pod
  type: NodePort
  ports:
    - port: 80
      targetPort: 5002
      nodePort: 32707 # you pick the number 30000-32767